// Generated by https://quicktype.io

/**
 * A release.
 */
export interface IReleaseByTagName {
	assets: ReleaseAsset[];
	assets_url: string;
	/**
	 * A GitHub user.
	 */
	author: AuthorObject;
	body?: null | string;
	body_html?: string;
	body_text?: string;
	created_at: string;
	/**
	 * The URL of the release discussion.
	 */
	discussion_url?: string;
	/**
	 * true to create a draft (unpublished) release, false to create a published one.
	 */
	draft: boolean;
	html_url: string;
	id: number;
	mentions_count?: number;
	name: null | string;
	node_id: string;
	/**
	 * Whether to identify the release as a prerelease or a full release.
	 */
	prerelease: boolean;
	published_at: null | string;
	reactions?: ReactionRollup;
	/**
	 * The name of the tag.
	 */
	tag_name: string;
	tarball_url: null | string;
	/**
	 * Specifies the commitish value that determines where the Git tag is created from.
	 */
	target_commitish: string;
	upload_url: string;
	url: string;
	zipball_url: null | string;
}

/**
 * Data related to a release.
 */
export interface ReleaseAsset {
	browser_download_url: string;
	content_type: string;
	created_at: string;
	download_count: number;
	id: number;
	label: null | string;
	/**
	 * The file name of the asset.
	 */
	name: string;
	node_id: string;
	size: number;
	/**
	 * State of the release asset.
	 */
	state: State;
	updated_at: string;
	uploader: null | SimpleUser;
	url: string;
}

/**
 * State of the release asset.
 */
export enum State {
	Open = 'open',
	Uploaded = 'uploaded',
}

/**
 * A GitHub user.
 */
export interface SimpleUser {
	avatar_url: string;
	email?: null | string;
	events_url: string;
	followers_url: string;
	following_url: string;
	gists_url: string;
	gravatar_id: null | string;
	html_url: string;
	id: number;
	login: string;
	name?: null | string;
	node_id: string;
	organizations_url: string;
	received_events_url: string;
	repos_url: string;
	site_admin: boolean;
	starred_at?: string;
	starred_url: string;
	subscriptions_url: string;
	type: string;
	url: string;
}

/**
 * A GitHub user.
 */
export interface AuthorObject {
	avatar_url: string;
	email?: null | string;
	events_url: string;
	followers_url: string;
	following_url: string;
	gists_url: string;
	gravatar_id: null | string;
	html_url: string;
	id: number;
	login: string;
	name?: null | string;
	node_id: string;
	organizations_url: string;
	received_events_url: string;
	repos_url: string;
	site_admin: boolean;
	starred_at?: string;
	starred_url: string;
	subscriptions_url: string;
	type: string;
	url: string;
}

export interface ReactionRollup {
	'+1': number;
	'-1': number;
	confused: number;
	eyes: number;
	heart: number;
	hooray: number;
	laugh: number;
	rocket: number;
	total_count: number;
	url: string;
}
